select
    codice_ente,
    anno,
    codice_voce,
    denominazione_ente,
    tipo_ente,
    codice_provincia,
    provincia,
    regione,
    codice_sottocomparto,
    descrizione_sottocomparto,
    codice_comparto,
    descrizione_comparto,
    sum(importo) as importo_totale,
    count(*) as righe,
    count(distinct periodo) as periodi_coperti,
    min(periodo) as periodo_min,
    max(periodo) as periodo_max,
    sum(importo) / 100.0 as importo_totale_eur,
    min(is_titolo_9) as is_titolo_9,
    min(macro_area) as macro_area,
    min(macro_categoria) as macro_categoria,
    descrizione_codice,
    min(has_codgest_match) as has_codgest_match
from clean_input
where codice_comparto = 'SAN'
group by
    codice_ente,
    anno,
    codice_voce,
    denominazione_ente,
    tipo_ente,
    codice_provincia,
    provincia,
    regione,
    codice_sottocomparto,
    descrizione_sottocomparto,
    codice_comparto,
    descrizione_comparto,
    descrizione_codice,
    has_codgest_match;
